FROM debian:9 

MAINTAINER Dalibor Menkovic <dalibor.menkovic@gmail.com>

ADD config /opt/config

RUN apt-get update && \
    apt-get install -y \
    locales \
    apt-transport-https \
    lsb-release \
    ca-certificates \
    gpg \
    vim \
    curl \
    wget \
    apache2 \
    git \
    zip \
    unzip \
    screen \
    whois \
    nfs-client \
    python-pip \
    python-yaml \
    locales 

#adding ondrejs repository 
RUN wget -O /etc/apt/trusted.gpg.d/php.gpg https://packages.sury.org/php/apt.gpg && \
    echo "deb https://packages.sury.org/php/ $(lsb_release -sc) main" > /etc/apt/sources.list.d/php.list
    
RUN apt-get update && apt-get install -y \
    php5.6 php5.6-cli php5.6-common php5.6-curl php5.6-dev php5.6-gd php5.6-intl php5.6-json php5.6-ldap php5.6-mbstring php5.6-mcrypt \
    php5.6-mysql php5.6-opcache php5.6-phpdbg php5.6-readline php5.6-soap php5.6-xml php5.6-zip php-gd php-gettext php-imagick php-log php-memcached php-mongodb php-mongo php-ssh2 
    
RUN apt-get install -y libapache2-mod-php5.6

RUN php -r " file_put_contents('cs.php', file_get_contents('https://getcomposer.org/installer')); if (hash_file('SHA384', 'cs.php') !== trim(file_get_contents('https://composer.github.io/installer.sig'))) { echo 'Corupted'.PHP_EOL; unlink('cs.php'); } " && \
    php cs.php --install-dir=/usr/local/bin --filename=composer  && \
    rm cs.php
    
RUN a2enmod rewrite && \
    a2enmod headers && \
    a2enmod expires && \
    pip install jinja && \
    python /opt/config/scripts/hosts.py 5.6

RUN adduser --disabled-password --gecos '' --uid 1005 apache-user

ADD config/php/5.6/php.ini /etc/php/5.6/apache2/php.ini
ADD config/apache/5.6/envvars /etc/apache2/envvars

EXPOSE 80

CMD ["/usr/sbin/apache2ctl","-DFOREGROUND"]
