FROM debian:9

MAINTAINER Dalibor Menkovic <dalibor.menkovic@gmail.com>

RUN echo "7.4" > /opt/version

RUN apt-get update && \
    apt-get install -y \
    locales \
    apt-transport-https \
    lsb-release \
    ca-certificates \
    gpg \
    curl \
    wget \
    apache2 \
    zip \
    unzip \
    nfs-client \
    python-pip \
    python-yaml \
    locales \
    cron

RUN wget -O /etc/apt/trusted.gpg.d/php.gpg https://packages.sury.org/php/apt.gpg
RUN echo "deb https://packages.sury.org/php/ $(lsb_release -sc) main" >> /etc/apt/sources.list.d/php.list

RUN apt-get update && \
    apt-get install -y \
    php7.4 php-common php7.4-cli php7.4-mysql \
    php-pear php7.4-dev php7.4-gd php7.4-memcached \
    php-gettext php7.4-xml php7.4-zip \
    libapache2-mod-php7.4 php7.4-curl \
    php-intl php7.4-imagick php7.4-mbstring php7.4-mongodb php7.4-json php-log

RUN php -r " file_put_contents('cs.php', file_get_contents('https://getcomposer.org/installer')); if (hash_file('SHA384', 'cs.php') !== trim(file_get_contents('https://composer.github.io/installer.sig'))) { echo 'Corupted'.PHP_EOL; unlink('cs.php'); } " && \
    php cs.php --install-dir=/usr/local/bin --filename=composer  && \
    rm cs.php

RUN a2enmod rewrite && \
    pip install jinja

RUN adduser --disabled-password --gecos '' --uid 1005 apache-user && groupmod -g 1005 apache-user

ADD config/apache/7.4/envvars /etc/apache2/envvars
ADD config/scripts/start.sh /bin/start_services.sh

EXPOSE 80

CMD ["/bin/bash","/bin/start_services.sh"]
