FROM debian:10

MAINTAINER Dalibor Menkovic <dalibor.menkovic@gmail.com>

ADD config /opt/config

RUN apt-get update && \
    apt-get install -y \
    locales \
    apt-transport-https \
    lsb-release \
    ca-certificates \
    gpg \
    vim \
    curl \
    wget \
    apache2 \
    git \
    zip \
    unzip \
    screen \
    whois \
    nfs-client \
    python-pip \
    python-yaml \
    locales

RUN wget -O /etc/apt/trusted.gpg.d/php.gpg https://packages.sury.org/php/apt.gpg
RUN echo "deb https://packages.sury.org/php/ $(lsb_release -sc) main" >> /etc/apt/sources.list.d/php.list


RUN apt-get update && \
    apt-get install -y \
    php8.1 php8.1-cli php8.1-mysql php-pear php8.1-dev php8.1-gd php8.1-memcached \
    php-gettext php8.1-xml php8.1-zip libapache2-mod-php8.1 php8.1-curl \
    php-intl php8.1-imagick php8.1-mbstring php8.1-mongodb php-json

RUN php -r " file_put_contents('cs.php', file_get_contents('https://getcomposer.org/installer')); if (hash_file('SHA384', 'cs.php') !== trim(file_get_contents('https://composer.github.io/installer.sig'))) { echo 'Corupted'.PHP_EOL; unlink('cs.php'); } " && \
    php cs.php --install-dir=/usr/local/bin --filename=composer  && \
    rm cs.php
    
RUN a2enmod rewrite && \
    a2enmod headers && \
    a2enmod expires && \
    pip install jinja && \
    python /opt/config/scripts/hosts.py 8.1

EXPOSE 80

CMD ["/usr/sbin/apache2ctl","-DFOREGROUND"]
